FROM d2slam:complete

COPY ./ /root/swarm_ws/src/D2SLAM
WORKDIR /root/swarm_ws
RUN   source "/opt/ros/noetic/setup.bash" && \
      catkin config -DCMAKE_BUILD_TYPE=Release \
            --cmake-args -DONNXRUNTIME_LIB_DIR=/usr/local/lib \
            -DONNXRUNTIME_INC_DIR=/usr/local/include -DUSE_CUDA=On&& \
      catkin build -j6
